language: node_js
node_js:
  - node

before_deploy:
  - npx jake
  - mkdir out
  - mv index.html package.json lib out/
  - rsync -av --include '@webcomponents/***' --include 'visible-children-observer/***' --exclude '*' node_modules/ out/node_modules
deploy:
  local-dir: out
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
