language: node_js
node_js:
  - node

before_deploy:
  - npx jake
  - mkdir out
  - npm prune --only=production
  - npm install --only=production @webcomponents/custom-elements
  - mv index.html package.json node_modules lib out/
deploy:
  local-dir: out
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
