language: node_js
node_js:
  - node

before_deploy:
  - npx jake
  - mkdir out
  - mv index.html lib out/
  - mkdir out/node_modules
  - rsync -avzn --list-only --include '@webcomponents/***' 'visible-children-observer/***' node_modules/ out/node_modules
deploy:
  local-dir: out
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
